#Input: Strings Text and Pattern.
#Output: Count(Text, Pattern)
#this program is to find the number of occurence of a pattern in the given string of a genome.

text = 'GGGCTGTTGTTGGTTAGCCAGTTGGTTACTTGGTTATTTGGTTATGATTTGGTTACCGCTTGGTTAGATTGGTTACTTGGTTATTGGTTAGTTGGTTATTTCGTTGGTTAGAGATTGGTTAAGATTTGGTTATTGGTTATGGTTGGTTACTTGGTTATTTGGTTATTGGTTATTTGGTTATTATTTGGTTAGTTGGTTATTTTGGTTATGCACTTGGTTATTGGTTATTGGTTAACCTTGGTTAGCCCTTTGGTTATTGGTTAATTGGTTAATTGGTTACGCTCCTTGGTTATTGGTTAATTGGTTAGGGTTTTGGTTAATGAGCCAAATTTGGTTATTGGTTAATCCGCAAGTTGGTTACGTTGGTTATACTTGGTTATTGGTTATACAGTTGGTTAGTTGGTTATCGTTGGTTACCCCTTGGTTACGCCCTTTGGTTATTGGTTACCTTGGTTAGCCGTTTGGTTAGTCTTGGTTAGGTTGGTTACAATCTCGCTTGGTTAAGTTGGTTATTTGGTTATTGGTTAGTTGGTTATTGGTTAGTATTGGTTACCCCAATTCTTGGTTACGATTGGTTAGTTGGTTATTGGTTATTGGTTAGTTGGAATGATTGGTTAATTGGTTATTGGTTAAATTGGTTATTGGTTAGGAATTGGTTAGGTTGGTTATGTTGGTTAGCTTGGTTAAGTTGGTTAAAAGTTGGTTACTAGTGTTTGGTTATTGGTTACTCTTGGTTATTGGTTAGGCTTGGTTAACTCCTACAAACTGTTGGTTAATTGGTTAAGTTTGGTTATTGGTTAGTGTGTTGGTTATTGGTTATGCTGTTGACTTGGTTACTTTGGTTATTTGGTTAGGTTGGTTAAGTTGGTTAACTTGGTTAGTAATGGTATTCTGTTGGTTATTGGTTACAGTTGGTTATTGGTTAGGACACCCCGGACTCCGTTTTGGTTAGTTGGTTATTGGTTATTGGTTATACTTTGGTTATTGGTTAGTTTTTGGTTAAGACATCTTGGTTATTGGTTATTCCGTTGGTTATTGGTTATTGGTTA'
pattern = 'TTGGTTATT'


def PatternCount(text, pattern):
    count = 0
    for i in range(len(text) - len(pattern)+1):
        if text[i:i+len(pattern)] == pattern:
            count += 1
    return count

      
print(PatternCount(text, pattern))